name: 'Hello World'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
    - uses: LouisBrunner/checks-action@v1.1.1
      id: integration-tests
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Integration tests
        status: in_progress
    - uses: LouisBrunner/checks-action@v1.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        check_id: ${{ steps.integration-tests.outputs.check_id }}
        conclusion: failure
        output: |
          {"summary": "OK, er ging iets mis"}