name: 'Integration Testing'
description: 'Run the integration tests and show the results'
inputs: 
  github_token:
    description: "GitHub Token"
    required: true
    default: ''
  api_key:
    description: "Api key"
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - uses: LouisBrunner/checks-action@v1.5.0
      id: integration-tests
      with:
        token: ${{ inputs.github_token }}
        name: Integration tests
        status: in_progress
    
    - uses: LouisBrunner/checks-action@v1.5.0
      with:
        token: ${{ inputs.github_token }}
        check_id: ${{ steps.integration-tests.outputs.check_id }}
        conclusion: failure
        output: |
          {"summary": "OK, er ging iets mis"}
    
    - name: test
      run: echo ${{ inputs.api_key }}