name: 'Integration Testing'
description: 'Run the integration tests and show the results'
inputs:
  API_KEY:
    description: "Api key"
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - uses: LouisBrunner/checks-action@v1.5.0
      id: integration-tests
      with:
        token: ${{ github.token }}
        name: Integration tests
        status: in_progress

    - name: Start tests
      id: start
      shell: bash
      run: |
        RESPONSE=$(curl -X POST https://hxp8z9xr67.execute-api.eu-west-1.amazonaws.com/prod/integration-test)
        echo "id=$RESPONSE" >> $GITHUB_OUTPUT
    
    - uses: LouisBrunner/checks-action@v1.5.0
      with:
        token: ${{ github.token }}
        check_id: ${{ steps.integration-tests.outputs.check_id }}
        conclusion: failure
        output: |
          {"summary": "OK, er ging iets mis"}
    
    - name: test
      shell: bash
      run: echo ${{ steps.start.id }}