name: 'Hello World'
description: 'Greet someone'
input: 
  token:
    description: "GitHub Token"
    required: true
runs:
  using: "composite"
  steps:
    - uses: LouisBrunner/checks-action@v1.5.0
      id: integration-tests
      with:
        token: ${{ inputs.token }}
        name: Integration tests
        status: in_progress
    - uses: LouisBrunner/checks-action@v1.5.0
      with:
        token: ${{ inputs.token }}
        check_id: ${{ steps.integration-tests.outputs.check_id }}
        conclusion: failure
        output: |
          {"summary": "OK, er ging iets mis"}