name: 'Integration Testing'
description: 'Run the integration tests and show the results'
inputs:
  secret:
    description: "Api key"
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - uses: LouisBrunner/checks-action@v1.5.0
      id: integration-tests
      with:
        token: ${{ github.token }}
        name: Integration tests
        status: in_progress
    
    - uses: LouisBrunner/checks-action@v1.5.0
      with:
        token: ${{ github.token }}
        check_id: ${{ steps.integration-tests.outputs.check_id }}
        conclusion: failure
        output: |
          {"summary": "OK, er ging iets mis"}
    
    - name: test
      shell: bash
      run: echo ${{ inputs.secret }} ${{ github.events }}