name: 'Integration Testing'
description: 'Run the integration tests and show the results'
inputs:
  API_KEY:
    description: "Api key"
    required: true
    default: ''
  API_ENDPOINT: 
    description: "Api endpoint"
    required: false
    default: 'https://hxp8z9xr67.execute-api.eu-west-1.amazonaws.com/prod/integration-test'
runs:
  using: "composite"
  steps:
    - name: Start tests
      id: start-tests
      shell: bash
      run: |
        EXECUTION_ARN=$(curl -X POST ${{ inputs.API_ENDPOINT }} -H "x-api-key: ${{ inputs.API_KEY }}" -H "Content-Type: application/json --fail")
        echo "execution-id=$(echo $EXECUTION_ARN | tail -c 37)" >> $GITHUB_OUTPUT

    - uses: LouisBrunner/checks-action@v1.5.0
      id: integration-tests
      with:
        token: ${{ github.token }}
        name: Integration tests
        status: in_progress
        output: |
          {"summary": "Integration testing started with exectionId: ${{ steps.start-tests.outputs.execution-id }}"}

    - name: Poll for result
      shell: bash
      run: |
        REPORT_URL="${{ inputs.API_ENDPOINT }}/${{ steps.start-tests.outputs.execution-id }}"
        STATUS='failure'
        COUNTER=0
        
        while true;
        do
            HTTP_STATUS=$(curl -X GET $REPORT_URL -i -s -H "x-api-key: ${{ inputs.API_KEY }}" -H "Content-Type: application/json" | grep HTTP/ | awk {'print $2'})
            if (($HTTP_STATUS == 200));then
                STATUS='success'
                break; 
            fi;
            if (($COUNTER == 6));then
                break;
            fi;
            sleep 5;
            COUNTER=$((COUNTER+1))
        done
        echo "http_status=$HTTP_STATUS" >> $GITHUB_ENV
        echo "status=$STATUS" >> $GITHUB_ENV

    - name: Get the cucumber report
      if: env.status == 'success'
      shell: bash
      run: |
        curl -X GET ${{ inputs.API_ENDPOINT }}/${{ steps.start-tests.outputs.execution-id }} \
          -o cucumber.report.json \
          -H "x-api-key: ${{ inputs.API_KEY }}" \
          -H "Content-Type: application/json" --fail
          cat cucumber.report.json
          echo '?'
    
    - uses: LouisBrunner/checks-action@v1.5.0
      if: env.status == 'success'
      with:
        token: ${{ github.token }}
        check_id: ${{ steps.integration-tests.outputs.check_id }}
        conclusion: success
    
    - uses: LouisBrunner/checks-action@v1.5.0
      if: env.status == 'failure'
      with:
        token: ${{ github.token }}
        check_id: ${{ steps.integration-tests.outputs.check_id }}
        conclusion: failure
        output: |
          {"summary": "OK, er ging iets mis"}

    - name: Convert cucumber report
      if: env.status == 'success'
      uses: deblockt/cucumber-report-annotations-action@v1.7
      with:
        access-token: ${{ github.token }}
        path: "cucumber.report.json"