name: 'Integration Testing'
description: 'Run the integration tests and show the results'
inputs:
  API_KEY:
    description: "Api key"
    required: true
    default: ''
runs:
  steps:
    - uses: LouisBrunner/checks-action@v1.5.0
      id: integration-tests
      with:
        token: ${{ github.token }}
        name: Integration tests
        status: in_progress
    
    - uses: LouisBrunner/checks-action@v1.5.0
      with:
        token: ${{ github.token }}
        check_id: ${{ steps.integration-tests.outputs.check_id }}
        conclusion: failure
        output: |
          {"summary": "OK, er ging iets mis"}
    
    - name: test
      shell: bash
      run: |
        ls -la
        echo ${{ steps.start.outputs.execution-id }}
    
    - name: test script
      shell: bash
      env:
        EXECUTION_ID: '123' # ${{ steps.start.outputs.execution-id }} #'229a68a4-409e-4abd-9b98-2d148d4275fc'
      run: ./test.sh

    - name: test script 2
      shell: bash
      env:
        EXECUTION_ID: '123' # ${{ steps.start.outputs.execution-id }} #'229a68a4-409e-4abd-9b98-2d148d4275fc'
      run: ./${GITHUB_WORKSPACE}/test.sh

    - name: test script 3
      shell: bash
      env:
        EXECUTION_ID: '123' # ${{ steps.start.outputs.execution-id }} #'229a68a4-409e-4abd-9b98-2d148d4275fc'
      run: bash test.sh

    - name: test script 4
      shell: bash
      env:
        EXECUTION_ID: '123' # ${{ steps.start.outputs.execution-id }} #'229a68a4-409e-4abd-9b98-2d148d4275fc'
      run: bash ${GITHUB_WORKSPACE}/test.sh